import React, { useState, useEffect } from "react";
import { base44 } from "@/api/base44Client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Copy, Users, TrendingUp, DollarSign, ExternalLink, Share2 } from "lucide-react";
import { toast } from "sonner";

export default function ReferralSystem({ agent, agentId }) {
  const [referredAgents, setReferredAgents] = useState([]);
  const [agentReferrals, setAgentReferrals] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadReferralData();
  }, [agentId]);

  const loadReferralData = async () => {
    if (!agentId) return;
    
    setLoading(true);
    try {
      const [referrals, players] = await Promise.all([
        base44.entities.AgentReferral.filter({ referrer_agent_id: agentId }),
        base44.entities.AgentPlayer.filter({ agent_id: agentId })
      ]);

      setAgentReferrals(referrals);
      
      // Get referred agent details
      if (referrals.length > 0) {
        const referredAgentIds = referrals.map(r => r.referred_agent_id);
        const allAgents = await base44.entities.Agent.list();
        const referred = allAgents.filter(a => referredAgentIds.includes(a.id));
        setReferredAgents(referred);
      }
    } catch (error) {
      console.error("Error loading referral data:", error);
    } finally {
      setLoading(false);
    }
  };

  const playerReferralUrl = agent?.tracking_code 
    ? `${window.location.origin}/referral-signup?ref=${agent.tracking_code}`
    : '';

  const agentReferralUrl = agent?.agent_referral_code
    ? `${window.location.origin}/become-agent?ref=${agent.agent_referral_code}`
    : '';

  const copyToClipboard = (text, type) => {
    navigator.clipboard.writeText(text);
    toast.success(`${type} link copied!`);
  };

  const totalReferralCommission = agentReferrals.reduce(
    (sum, r) => sum + (r.total_commission_earned || 0),
    0
  );

  const activeReferrals = agentReferrals.filter(r => r.status === 'active').length;

  return (
    <div className="space-y-6">
      {/* Stats Cards */}
      <div className="grid md:grid-cols-3 gap-6">
        <Card className="bg-gray-900 border-gray-800">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-gray-400 flex items-center">
              <Users className="w-4 h-4 mr-2 text-blue-400" />
              Agents Referred
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-white">{agentReferrals.length}</div>
            <p className="text-xs text-green-400 mt-1">{activeReferrals} active</p>
          </CardContent>
        </Card>

        <Card className="bg-gray-900 border-gray-800">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-gray-400 flex items-center">
              <TrendingUp className="w-4 h-4 mr-2 text-purple-400" />
              Referral Revenue
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-purple-400">
              ${agentReferrals.reduce((sum, r) => sum + (r.total_revenue_generated || 0), 0).toFixed(0)}
            </div>
            <p className="text-xs text-gray-500 mt-1">Generated by referrals</p>
          </CardContent>
        </Card>

        <Card className="bg-gray-900 border-gray-800">
          <CardHeader className="pb-2">
            <CardTitle className="text-sm font-medium text-gray-400 flex items-center">
              <DollarSign className="w-4 h-4 mr-2 text-green-400" />
              Commission Earned
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="text-3xl font-bold text-green-400">
              ${totalReferralCommission.toFixed(2)}
            </div>
            <p className="text-xs text-gray-500 mt-1">10% of referral revenue</p>
          </CardContent>
        </Card>
      </div>

      <Tabs defaultValue="player" className="space-y-6">
        <TabsList className="bg-gray-900 border-gray-800 grid grid-cols-2">
          <TabsTrigger value="player" className="data-[state=active]:bg-emerald-500/20">
            Player Referrals
          </TabsTrigger>
          <TabsTrigger value="agent" className="data-[state=active]:bg-purple-500/20">
            Agent Referrals
          </TabsTrigger>
        </TabsList>

        {/* Player Referrals Tab */}
        <TabsContent value="player">
          <Card className="bg-gray-900 border-gray-800">
            <CardHeader>
              <CardTitle className="text-white">Player Referral Link</CardTitle>
              <p className="text-gray-400 text-sm">
                Share this link with players. When they sign up through it, they'll be automatically tracked.
              </p>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex gap-2">
                <Input
                  value={playerReferralUrl}
                  readOnly
                  className="bg-gray-800 border-gray-700 text-white font-mono text-sm"
                />
                <Button
                  onClick={() => copyToClipboard(playerReferralUrl, 'Player referral')}
                  className="bg-emerald-600 hover:bg-emerald-700 flex-shrink-0"
                >
                  <Copy className="w-4 h-4 mr-2" />
                  Copy
                </Button>
              </div>

              <div className="flex gap-2">
                <Button
                  variant="outline"
                  onClick={() => window.open(playerReferralUrl, '_blank')}
                  className="flex-1 border-gray-700 text-gray-300"
                >
                  <ExternalLink className="w-4 h-4 mr-2" />
                  Preview Link
                </Button>
                <Button
                  variant="outline"
                  className="flex-1 border-gray-700 text-gray-300"
                  onClick={() => {
                    if (navigator.share) {
                      navigator.share({
                        title: 'Join Through My Link',
                        text: 'Sign up for exclusive gaming offers!',
                        url: playerReferralUrl
                      });
                    } else {
                      toast.info("Share feature not available on this browser");
                    }
                  }}
                >
                  <Share2 className="w-4 h-4 mr-2" />
                  Share
                </Button>
              </div>

              <div className="p-4 bg-blue-500/10 border border-blue-500/30 rounded-lg">
                <p className="text-sm text-blue-400">
                  💡 <strong>Pro Tip:</strong> Add this link to your website, social media bio, or email signature to maximize referrals.
                </p>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        {/* Agent Referrals Tab */}
        <TabsContent value="agent">
          <Card className="bg-gray-900 border-gray-800">
            <CardHeader>
              <CardTitle className="text-white">Agent Referral Link</CardTitle>
              <p className="text-gray-400 text-sm">
                Refer other agents and earn <strong className="text-purple-400">10% of their revenue for life!</strong>
              </p>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex gap-2">
                <Input
                  value={agentReferralUrl}
                  readOnly
                  className="bg-gray-800 border-gray-700 text-white font-mono text-sm"
                />
                <Button
                  onClick={() => copyToClipboard(agentReferralUrl, 'Agent referral')}
                  className="bg-purple-600 hover:bg-purple-700 flex-shrink-0"
                >
                  <Copy className="w-4 h-4 mr-2" />
                  Copy
                </Button>
              </div>

              <div className="p-4 bg-purple-500/10 border border-purple-500/30 rounded-lg">
                <h4 className="font-semibold text-purple-400 mb-2">Agent Referral Benefits:</h4>
                <ul className="space-y-1 text-sm text-gray-300">
                  <li>✓ Earn 10% of referred agent's total revenue</li>
                  <li>✓ Lifetime commission on all their earnings</li>
                  <li>✓ No limit on number of agents you can refer</li>
                  <li>✓ Passive income stream that grows with your network</li>
                </ul>
              </div>

              {/* Referred Agents List */}
              {agentReferrals.length > 0 ? (
                <div className="mt-6">
                  <h4 className="text-white font-semibold mb-3">Your Referred Agents</h4>
                  <div className="space-y-2">
                    {agentReferrals.map((referral) => {
                      const referredAgent = referredAgents.find(a => a.id === referral.referred_agent_id);
                      return (
                        <div
                          key={referral.id}
                          className="flex items-center justify-between p-3 bg-gray-800/50 rounded-lg"
                        >
                          <div>
                            <div className="font-semibold text-white">
                              {referredAgent?.agent_name || 'Agent'}
                            </div>
                            <div className="text-xs text-gray-400">
                              Joined {new Date(referral.referral_date).toLocaleDateString()}
                            </div>
                          </div>
                          <div className="text-right">
                            <div className="text-green-400 font-semibold">
                              ${(referral.total_commission_earned || 0).toFixed(2)}
                            </div>
                            <Badge className={
                              referral.status === 'active' ? 'bg-green-500/20 text-green-400' :
                              'bg-yellow-500/20 text-yellow-400'
                            }>
                              {referral.status}
                            </Badge>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ) : (
                <div className="text-center py-8 text-gray-500">
                  <Users className="w-12 h-12 mx-auto mb-3 opacity-50" />
                  <p>No agent referrals yet. Start sharing your link!</p>
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}